// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/31/2024, 15:55:38
const configMerger = require("C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/plugins/**/*.{js,ts,mjs}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/composables/**/*.{js,ts,mjs}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/utils/**/*.{js,ts,mjs}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MyPC One Pro K-24/Documents/xiipplg3/fahrul/smkn4/app.config.{js,ts,mjs}"] } }));

module.exports = config
